### ISSUE TITLE
Use of pre-installed Algorithms

### ISSUE THREAD

**Issue by jetlime** [LBacchiani/session-subtyping-tool#1]
Hello,

__1.__ I am trying to use your session subtyping tool for a semester project at my University. Following your documentation in the readmefile, it is unclear to me how to correctly use the pre-installed algorithms. While trying to apply them (for all the algortims), I get the following error :
```sh
asynchronous-subtyping\\ is not recognized as an internal or external command,
an ex\x82cutable program or a command file.
```
__2.__ Furthermore, it is indicated in the documentation that examples would be available on the [release page](https://github.com/LBacchiani/session-subtyping-tool/releases). However I don't find them there. Where could I find examples and corresponding expected outputs, in order to test and explore your software?

Many thanks for your help,

Paul Houssel

**Comment by LBacchiani** [comment]
1. According to what it is written in the README file, if you are not using the standalone version, you have to compile Haskell source file and move them following the instructions in Section "Compiling Haskell sources". Then you have to launch SessionSubtypingTool.py). From the error message you have posted, it seems that you are trying to execute "asynchronous-subtyping" that is a folder
2. The examples are in "paper-types.zip" (if you want to know the expected output you should look at the related paper called [A session subtyping tool](https://link.springer.com/chapter/10.1007/978-3-030-78142-2_6). In "other-examples.zip" you can find some random session types (we have not inserted the expected output).

Best,
    Lorenzo Bacchiani
